### ISSUE TITLE
ToDo Liste

### ISSUE THREAD

**Issue by KimZuel** [Gamemaker-AG/basement-attack#2]
- [x] Pathfinding (HO)
- [x] path following (HO)
- [x] spawners
- [x] despawning when goal is reached
- [x] don't shows paths for dead opponents
- [x] fix giant delta times when tab loses and re-gains focus (move update logic to service workers or similar) same problem can be observed when an alert steals the game's focus
- [x] tower attacking & bullet rendering
- [x] Kosten für die Tower
- [x] Menü rechts -> Gold, Wave, ...
- [x] don't allow building towers if resources <= 0
- [x] use single source shortest path for quicker path finding (HO)
- [x] support for two goal fields? For symmetry (HO)
- [x] wave spawning
- [x] Spawner in the center
- [x] health indicator for creeps
- [x] creep attacking
- [x] Disable sound by default or store state in cookies
- [x] Useful ui for when you are out of money
- [x] Further performance improvements
- [x] Nice graphics for menu
- [ ] Musik / Soundeffekte
- [ ] Credits
- [ ] balancing
- [ ] proper game over state
  - [ ] Show a score (we need to come up with one first)
- [ ] Separate mute buttons for music and SFX
- [ ] show (maybe only some) creep stats in the ui
- [ ] fancy website
- [ ] tower implementations
    - [ ] splash + explosion
        - [ ] venom
        - [ ] frost
    - [ ] heal (drones / area)
        - [ ] heal + damage boost
        - [ ] missile swarm bullets
    - [x] machine gun
        - [ ] cool bullets
        - [ ] double machine gun (higher fire rate) + ministun
        - [ ] incremental damage laser
    - [x] tank
        - [ ] more tank + bomb on death
        - [ ] cactus (damaging attacking creeps)
- [ ] tower graphics
    - [ ] splash + explosion
        - [ ] venom
        - [ ] frost
    - [ ] heal (drones / area)
        - [ ] heal
        - [x] missile swarm
    - [ ] machine gun
        - [ ] cool bullets
        - [ ] double machine gun
        - [ ] laser incremental damage
    - [x] tank
        - [x] more tank
        - [x] cactus (damaging attacking creeps)
- [ ] splash explosion graphics
- [ ] more creeps (kangaroo creep?)
- [ ] ~~towers facing a random direction when building them~~ Don't try this, it will fuck you up!
- [ ] tower targeting strategy
- [ ] next wave / creep info
- [ ] main menu button text
- [ ] fix zero-range creeps not being recognized in pathfinding (not sure about what the issue is exactly)
- [ ] prevent towers being upgradable after they die (this is possible by bringing up the upgrade menu and waiting until the tower dies)

## maybe someday
- [ ] web workers for path finding
- [ ] Touchscreen controls
